#!/usr/local/bin/python3

import os, sys, ROOT
import style

ROOT.gROOT.SetBatch()

pstyle = style.SetPlotStyle()

f = ROOT.TFile.Open("higgsCombineTest.MultiDimFit.mH120.root", "READ")
limit = f.Get("limit")
c1 = ROOT.TCanvas("c", "c", 600, 540)
#limit.Draw("2*deltaNLL:r*0.0028*100>>h","2*deltaNLL<10")
limit.Draw("2*deltaNLL:r*0.01054*100>>h","2*deltaNLL<10")
gr = ROOT.gPad.GetPrimitive("Graph").Clone("gr")
c1.Clear()
ROOT.gStyle.SetOptStat(0)
gr.Draw("AC")
gr.GetHistogram().SetTitle("")
#gr.GetHistogram().GetXaxis().SetTitle("B(t #rightarrow hc) [%]")
gr.GetHistogram().GetXaxis().SetTitle("B(t #rightarrow Sc) [%]")
gr.GetHistogram().GetYaxis().SetTitle("2#Delta NLL")
gr.GetHistogram().GetYaxis().SetRangeUser(0., 10.)
s1 = ROOT.TLine(gr.GetHistogram().GetXaxis().GetXmin(), 1.00, gr.GetHistogram().GetXaxis().GetXmax(), 1.00)
s1.SetLineColor(ROOT.kGray)
s1.SetLineStyle(2)
s1.SetLineWidth(2)
s1.Draw()                    
s2 = ROOT.TLine(gr.GetHistogram().GetXaxis().GetXmin(), 3.84, gr.GetHistogram().GetXaxis().GetXmax(), 3.84)
s2.SetLineColor(ROOT.kGray)
s2.SetLineStyle(2)
s2.SetLineWidth(2)
s2.Draw()
cl68 = ROOT.TLatex(0.81, 0.26, "68% CL")
cl68.SetNDC()
cl68.SetTextSize(0.02)
cl68.SetTextColor(ROOT.kGray)
cl68.Draw()
cl95 = ROOT.TLatex(0.81, 0.475, "95% CL")
cl95.SetNDC()
cl95.SetTextSize(0.02)
cl95.SetTextColor(ROOT.kGray)
cl95.Draw()
c1.Print("nll.pdf")
f.Close()