################## BACKGROUND ##################
processes:
  - name: ee2tt_bWbW_W2ln 
    process: TTbar_leptonic 
    type: background 
    events: 100000 
    xsec: 0.02147

  - name: ee2tt_bWbW_W2lnW2qq
    process: TTbar_semileptonic
    type: background
    events: 100000
    xsec: 0.1288

  - name: ee2tt_bWbW_W2qq
    process: TTbar_hadronic
    type: background
    events: 100000
    xsec: 0.193
    
  #################### SIGNAL ####################

  - name: ee2tt_cSbW_S2bb_M15
    process: cSbb_M15
    type: signal
    events: 100000
    xsec: 0.001663
mass: 15
bdt_cut: 0.97