################## BACKGROUND ##################
processes:
  - name: ee2tt_bWbW_W2ln 
    process: TTbar_leptonic 
    type: background 
    events: 100000 
    xsec: 0.02147

  - name: ee2tt_bWbW_W2lnW2qq
    process: TTbar_semileptonic
    type: background
    events: 100000
    xsec: 0.1288

  - name: ee2tt_bWbW_W2qq
    process: TTbar_hadronic
    type: background
    events: 100000
    xsec: 0.193
    
  #################### SIGNAL ####################

  - name: ee2tt_cHbW_h2bb
    process: cHbb
    type: signal
    events: 100000
    xsec: 0.0003737
mass: 125
bdt_cut: 0.97

#- name: ee2tt_cSbW_S2bb_M10
#  process: cSbb_M10
#  type: signal
#  events: 100000
#  xsec: 0.001678
#- name: ee2tt_cSbW_S2bb_M15
#  process: cSbb_M15
#  type: signal
#  events: 100000
#  xsec: 0.001663
#- name: ee2tt_cSbW_S2bb_M20
#  process: cSbb_M20
#  type: signal
#  events: 100000
#  xsec: 0.001643
#- name: ee2tt_cSbW_S2bb_M50
#  process: cSbb_M50
#  type: signal
#  events: 100000
#  xsec: 0.001415
#- name: ee2tt_uHbW_h2bb
#  process: uHbb
#  type: signal
#  events: 100000
#  xsec: 0.0003737
#- name: ee2tt_uSbW_S2bb_M10
#  process: uSbb_M10
#  type: signal
#  events: 100000
#  xsec: 0.001678
#- name: ee2tt_uSbW_S2bb_M15
#  process: uSbb_M15
#  type: signal
#  events: 100000
#  xsec: 0.001663
#- name: ee2tt_uSbW_S2bb_M20
#  process: uSbb_M20
#  type: signal
#  events: 100000
#  xsec: 0.001643
#- name: ee2tt_uSbW_S2bb_M50
#  process: uSbb_M50
#  type: signal
#  events: 100000
#  xsec: 0.001415